import { eslint, extensions, toEs } from '../helpers'
import tseslint from 'typescript-eslint'
// @ts-expect-error
import typescriptEnumPlugin from 'eslint-plugin-typescript-enum'
// @ts-expect-error
import securityPlugin from 'eslint-plugin-security'
import unicornPlugin from 'eslint-plugin-unicorn'

const eslintRules: eslint.RulesRecord = {
  'no-var': ['error'],
  eqeqeq: [
    'error',
    'always',
    {
      null: 'never',
    },
  ],
  'no-debugger': ['error'],
  camelcase: ['warn'],
  'no-self-compare': ['warn'],
  'no-unused-private-class-members': ['warn'],
  'default-case': ['error'],
  'default-case-last': ['error'],
  'no-caller': ['error'],
  'no-console': ['error'],
  'no-alert': ['error'],
  'no-with': ['error'],
  'prefer-const': ['error'],
  'symbol-description': ['error'],
  'block-scoped-var': ['error'],
  'no-bitwise': ['warn'],
  'no-new': ['error'],
  'use-isnan': [
    'error',
    {
      enforceForSwitchCase: true,
      enforceForIndexOf: true,
    },
  ],
  'no-empty-pattern': ['error'],
  'no-object-constructor': ['error'],
  'no-new-native-nonconstructor': ['error'],
  'no-octal': ['error'],
  'no-octal-escape': ['warn'],
  'no-obj-calls': ['error'],
  'prefer-rest-params': ['error'],
  'no-script-url': ['error'],
  'prefer-regex-literals': [
    'warn',
    {
      disallowRedundantWrapping: true,
    },
  ],
  'valid-typeof': ['error'],
  radix: ['error', 'always'],
  'no-duplicate-imports': ['error'],
  'no-constant-condition': [
    'warn',
    {
      checkLoops: true,
    },
  ],
  'require-yield': ['error'],
  'getter-return': ['error'],
  'no-new-wrappers': ['error'],
  'no-useless-rename': ['error'],
  'one-var': ['error', 'never'],
  'no-useless-computed-key': [
    'error',
    {
      enforceForClassMembers: true,
    },
  ],
  'object-shorthand': [
    'error',
    'always',
    {
      avoidExplicitReturnArrows: true,
    },
  ],
  'no-return-assign': ['error'],
  'no-proto': ['error'],
  'no-useless-concat': ['error'],
  'for-direction': ['warn'],
  'prefer-numeric-literals': ['error'],
  'no-constructor-return': ['error'],
  'no-dupe-args': ['error'],
  'no-shadow-restricted-names': ['warn'],
  'no-unused-labels': ['error'],
  'no-extra-label': ['error'],
  'no-extend-native': ['error'],
  'no-dupe-keys': ['error'],
  'no-extra-bind': ['error'],
  'no-eval': ['error'],
  'no-delete-var': ['error'],
  'no-extra-boolean-cast': ['error'],
  'no-global-assign': ['error'],
  'prefer-spread': ['warn'],
  'no-iterator': ['error'],
  'no-label-var': ['error'],
  'no-lonely-if': ['error'],
  'no-fallthrough': ['error'],
  'no-negated-condition': ['warn'],
  'no-self-assign': ['error'],
  'no-prototype-builtins': ['error'],
  'prefer-promise-reject-errors': ['warn'],
  'no-nonoctal-decimal-escape': ['error'],
  'no-func-assign': ['error'],
  'no-import-assign': ['error'],
  'prefer-exponentiation-operator': ['error'],
  'no-sparse-arrays': ['error'],
  'no-implicit-coercion': [
    'error',
    {
      disallowTemplateShorthand: true,
    },
  ],
  'no-ex-assign': ['error'],
  'no-empty-static-block': ['error'],
  'no-dupe-else-if': ['error'],
  'no-empty': [
    'error',
    {
      allowEmptyCatch: true,
    },
  ],
  'no-duplicate-case': ['error'],
  'no-const-assign': ['error'],
  'constructor-super': ['error'],
  'logical-assignment-operators': ['error'],
  'no-new-func': ['error'],
  'no-unneeded-ternary': ['error'],
  'no-useless-return': ['warn'],
  'operator-assignment': ['error'],
  'no-cond-assign': ['warn', 'always'],
  'no-compare-neg-zero': ['warn'],
  'no-class-assign': ['error'],
  'no-case-declarations': ['error'],
  'no-useless-escape': ['error'],
  'no-useless-catch': ['error'],
  'no-undef-init': ['error'],
  'no-setter-return': ['error'],
  'prefer-arrow-callback': ['warn'],
  'no-unsafe-optional-chaining': [
    'warn',
    {
      disallowArithmeticOperators: true,
    },
  ],
  'no-unreachable-loop': ['warn'],
  'no-unreachable': ['error'],
  'no-unsafe-finally': ['error'],
  'no-useless-call': ['error'],
  'prefer-destructuring': [
    'warn',
    {
      object: true,
      array: false,
    },
  ],
  'no-this-before-super': ['error'],
  'no-promise-executor-return': ['error'],
  'no-async-promise-executor': ['error'],
  'no-constant-binary-expression': ['warn'],
  'no-implicit-globals': ['error'],
  'consistent-return': ['warn'],
  'dot-notation': ['warn'],
  'require-await': ['warn'],
  'no-return-await': ['warn'],
  'no-implied-eval': ['error'],
  'no-throw-literal': ['error'],
  'prefer-object-spread': ['warn'],
  'guard-for-in': ['warn'],
  'require-atomic-updates': ['warn'],
  'no-loop-func': ['warn'],
  'no-unmodified-loop-condition': ['warn'],
}

const typescriptEslintRules: eslint.RulesRecord = {
  '@typescript-eslint/no-array-constructor': ['error'],
  '@typescript-eslint/default-param-last': ['error'],
  '@typescript-eslint/no-empty-function': ['error'],
  '@typescript-eslint/no-dupe-class-members': ['error'],
  '@typescript-eslint/no-invalid-this': ['error'],
  '@typescript-eslint/no-loop-func': ['warn'],
  'no-loss-of-precision': ['error'],
  '@typescript-eslint/no-redeclare': [
    'error',
    {
      ignoreDeclarationMerge: false,
    },
  ],
  '@typescript-eslint/adjacent-overload-signatures': ['error'],
  '@typescript-eslint/array-type': [
    'error',
    {
      default: 'array',
      readonly: 'array',
    },
  ],
  '@typescript-eslint/ban-ts-comment': [
    'error',
    {
      'ts-expect-error': false,
      'ts-check': false,
      'ts-ignore': true,
      'ts-nocheck': true,
    },
  ],
  '@typescript-eslint/ban-tslint-comment': ['error'],
  '@typescript-eslint/no-empty-object-type': ['warn'],
  '@typescript-eslint/no-unsafe-function-type': ['warn'],
  '@typescript-eslint/no-wrapper-object-types': ['warn'],
  '@typescript-eslint/consistent-generic-constructors': [
    'error',
    'constructor',
  ],
  '@typescript-eslint/consistent-indexed-object-style': ['warn', 'record'],
  '@typescript-eslint/consistent-type-assertions': ['error'],
  '@typescript-eslint/consistent-type-imports': [
    'error',
    {
      prefer: 'type-imports',
      fixStyle: 'separate-type-imports',
    },
  ],
  '@typescript-eslint/explicit-member-accessibility': [
    'error',
    {
      overrides: { constructors: 'no-public' },
    },
  ],
  '@typescript-eslint/method-signature-style': ['error', 'property'],
  '@typescript-eslint/naming-convention': [
    'error',
    {
      selector: 'interface',
      format: ['PascalCase'],
    },
    {
      selector: 'typeLike',
      format: ['PascalCase'],
    },
  ],
  '@typescript-eslint/triple-slash-reference': ['warn'],
  '@typescript-eslint/unified-signatures': ['warn'],
  '@typescript-eslint/no-unused-vars': [
    'error',
    {
      argsIgnorePattern: '^_',
    },
  ],
  '@typescript-eslint/no-dynamic-delete': ['warn'],
  '@typescript-eslint/no-explicit-any': ['warn'],
  '@typescript-eslint/no-extra-non-null-assertion': ['error'],
  '@typescript-eslint/no-import-type-side-effects': ['error'],
  '@typescript-eslint/no-inferrable-types': ['warn'],
  '@typescript-eslint/no-misused-new': ['error'],
  '@typescript-eslint/no-unused-expressions': ['error'],
  '@typescript-eslint/no-useless-constructor': ['error'],
  '@typescript-eslint/prefer-as-const': ['error'],
  '@typescript-eslint/no-unnecessary-type-constraint': ['error'],
  '@typescript-eslint/prefer-function-type': ['error'],
  '@typescript-eslint/no-unsafe-declaration-merging': ['error'],
  '@typescript-eslint/no-non-null-asserted-nullish-coalescing': ['error'],
  '@typescript-eslint/no-non-null-asserted-optional-chain': ['error'],
  '@typescript-eslint/no-non-null-assertion': ['warn'],
  '@typescript-eslint/no-this-alias': ['warn'],
}

const typescriptEnumRules: eslint.RulesRecord = {
  'typescript-enum/no-enum': ['error'],
}

const securityRules: eslint.RulesRecord = {
  'security/detect-bidi-characters': ['warn'],
  'security/detect-buffer-noassert': ['warn'],
  'security/detect-child-process': ['warn'],
  'security/detect-eval-with-expression': ['warn'],
  'security/detect-new-buffer': ['warn'],
  'security/detect-non-literal-regexp': ['warn'],
  'security/detect-unsafe-regex': ['warn'],
  'security/detect-non-literal-require': ['warn'],
  'security/detect-pseudoRandomBytes': ['warn'],
  'security/detect-non-literal-fs-filename': ['warn'],
  'security/detect-object-injection': ['warn'],
  'security/detect-possible-timing-attacks': ['warn'],
}

const unicornRules: eslint.RulesRecord = {
  'unicorn/consistent-destructuring': ['warn'],
  'unicorn/custom-error-definition': ['error'],
  'unicorn/error-message': ['error'],
  'unicorn/new-for-builtins': ['error'],
  'unicorn/no-array-push-push': ['error'],
  'unicorn/no-document-cookie': ['warn'],
  'unicorn/no-empty-file': ['error'],
  'unicorn/no-instanceof-array': ['error'],
  'unicorn/filename-case': [
    'warn',
    {
      cases: {
        camelCase: true,
        pascalCase: true,
      },
    },
  ],
  'unicorn/no-new-buffer': ['error'],
  'unicorn/no-unnecessary-await': ['warn'],
  'unicorn/no-useless-length-check': ['error'],
  'unicorn/no-useless-spread': ['error'],
  'unicorn/no-useless-switch-case': ['error'],
  'unicorn/no-useless-undefined': ['warn'],
  'unicorn/no-zero-fractions': ['error'],
  'unicorn/prefer-array-flat-map': ['error'],
  'unicorn/prefer-date-now': ['error'],
  'unicorn/prefer-default-parameters': ['error'],
  'unicorn/prefer-export-from': [
    'error',
    {
      ignoreUsedVariables: true,
    },
  ],
  'unicorn/prefer-modern-math-apis': ['error'],
  'unicorn/prefer-node-protocol': ['error'],
  'unicorn/prefer-optional-catch-binding': ['error'],
  'unicorn/prefer-query-selector': ['warn'],
  'unicorn/prefer-spread': ['warn'],
  'unicorn/prefer-string-replace-all': ['warn'],
  'unicorn/prefer-string-slice': ['error'],
  'unicorn/prefer-string-trim-start-end': ['error'],
  'unicorn/prefer-switch': ['warn'],
  'unicorn/prefer-type-error': ['warn'],
  'unicorn/require-array-join-separator': ['error'],
  'unicorn/require-number-to-fixed-digits-argument': ['error'],
  'unicorn/throw-new-error': ['warn'],
}

export const general: eslint.FlatConfig = [
  {
    files: extensions.toGlobs(extensions.jsts),
    languageOptions: eslint.languageOptionsTypeScript,
    plugins: {
      '@typescript-eslint': tseslint.plugin,
      'typescript-enum': typescriptEnumPlugin,
      security: securityPlugin,
      unicorn: toEs(unicornPlugin),
    },
    rules: {
      ...eslintRules,
      ...typescriptEslintRules,
      ...typescriptEnumRules,
      ...securityRules,
      ...unicornRules,
    },
  },
]
