import { definePlugin, stripPrefix } from '../plugins'

export default definePlugin({
  packageName: 'eslint-plugin-jsdoc',
  prefix: 'jsdoc',
  docsLinkBuilder: ruleName => {
    return `https://github.com/gajus/eslint-plugin-jsdoc/blob/main/docs/rules/${stripPrefix(
      ruleName
    )}.md`
  },
  rules: [
    'jsdoc/check-access',
    'jsdoc/check-alignment',
    'jsdoc/check-examples',
    'jsdoc/check-indentation',
    'jsdoc/check-line-alignment',
    'jsdoc/check-param-names',
    'jsdoc/check-property-names',
    'jsdoc/check-syntax',
    'jsdoc/check-tag-names',
    'jsdoc/check-types',
    'jsdoc/check-values',
    'jsdoc/empty-tags',
    'jsdoc/implements-on-classes',
    'jsdoc/imports-as-dependencies',
    'jsdoc/informative-docs',
    'jsdoc/match-description',
    'jsdoc/match-name',
    'jsdoc/multiline-blocks',
    'jsdoc/no-bad-blocks',
    'jsdoc/no-blank-block-descriptions',
    'jsdoc/no-blank-blocks',
    'jsdoc/no-defaults',
    'jsdoc/no-missing-syntax',
    'jsdoc/no-multi-asterisks',
    'jsdoc/no-restricted-syntax',
    'jsdoc/no-types',
    'jsdoc/no-undefined-types',
    'jsdoc/require-asterisk-prefix',
    'jsdoc/require-description-complete-sentence',
    'jsdoc/require-description',
    'jsdoc/require-example',
    'jsdoc/require-file-overview',
    'jsdoc/require-hyphen-before-param-description',
    'jsdoc/require-jsdoc',
    'jsdoc/require-param-description',
    'jsdoc/require-param-name',
    'jsdoc/require-param-type',
    'jsdoc/require-param',
    'jsdoc/require-property-description',
    'jsdoc/require-property-name',
    'jsdoc/require-property-type',
    'jsdoc/require-property',
    'jsdoc/require-returns-check',
    'jsdoc/require-returns-description',
    'jsdoc/require-returns-type',
    'jsdoc/require-returns',
    'jsdoc/require-throws',
    'jsdoc/require-yields-check',
    'jsdoc/require-yields',
    'jsdoc/sort-tags',
    'jsdoc/tag-lines',
    'jsdoc/text-escaping',
    'jsdoc/valid-types',
  ],
})
